HubSpot/cms-event-registration

- resources/events.hubdb.json
The sample hubdb table reference some incorrect table columns which caused "There are NaN spots left" to display instead of the correct number of remaining spots.
> Fix table column names

- src/components/EventDetails.js
This didn't make it into the initial commit prior to release. Adds correct `isFull` calculation to the event details registration form.
> Fix 'join waitlist' state for at-capacity events' registration forms

- src/components/EventDetails.scss
- src/scss/App.scss
In sum, there were inconsistent margins between page titles on '/events', '/my-event', and '/my-events' pages. 
Each of these event titles was assigned the class "event-header." I loaded each page and compared the margins for each event title, and I narrowed the problem down to the `margin-bottom` property which had been set to 0. 
I believe that the margin-bottom had been set to 0, because on the '/my-event' page (individual event information), there was too much space between the event title and the event cards beneath it. I investigated the event cards and found that the top margin on the event image was too wide. 
My solution was to remove the margin-bottom property from the event-header class and to remove the top margin from the events image.
cc @levinkeo @gcorne @anthmatic
> Fix margins on event titles

- README.md
- package.json
- yarn.lock
Fixes #9 
I've added a "Usage" section to the README with brief explanations for all the scripts listed in the `package.json` file, except for `yarn eslint.` This command seems a bit redundant taken with `yarn lint`; perhaps we can delete it? 
cc @gcorne @levinkeo @anthmatic
> Document different scripts

- src/modules/events-app.module/fields.json
- src/modules/events-app.module/module.html
Fixes #7.
Preview: https://akemmerle-7428138.hs-sites.com/events
I've added four color fields to the Events app module: one to control the background color of the module, one to control the event card background color, one to control the font color, and one to control the calendar's highlight color for the current date. 
If anyone has suggestions for more color fields, I'm all ears. I'm planning to continue working on this tomorrow and perhaps into next week. 
Also, if someone could look over the `module.html` file and review how I implemented the color changes, I'd really appreciate it. 
cc @levinkeo @gcorne @anthmatic
> Add color fields to events app module

- src/modules/upcoming-events.module/fields.json
- src/modules/upcoming-events.module/module.html
- src/scss/upcoming-events.scss
Fixes #17 
I've added five color fields to control:
-the module's background color
-the event cards' background color
-the text color
-the module's title color 
-the event cards' title color 
Per @levinkeo's suggestion here (https://github.com/HubSpot/cms-event-registration/pull/15#discussion_r407559486), I've scoped the CSS, but please let me know if I need to be more specific :) 
If anyone has any suggestions about adding/subtracting color fields or streamlining the code, I'm all ears 
cc @gcorne @levinkeo @anthmatic
> Add color fields to the upcoming events module

- src/modules/upcoming-events.module/fields.json
- src/modules/upcoming-events.module/module.html
- src/scss/upcoming-events.scss
I reverted #19 because it was failing the ESLint build checks. I've now edited the Upcoming Events module's `fields.json` and `module.html` to comply with our style guides.
> Reverts #23 and adds color fields to Upcoming Events module again

- README.md
- package.json
- scripts/createHubDb.js
- yarn.lock
Instead of using the CMS CLI, this uses CMS-LIB to check if a table exists before creating it, which will prevent issues where multiple tables with the same name get created in a portal.
Fixes #10
> Only create hubdb table if it doesn't exist

- src/modules/events-app.module/fields.json
- src/modules/events-app.module/module.html
- src/modules/upcoming-events.module/module.html
Reverts HubSpot/cms-event-registration#26 and adds color fields to the events app module once again. 
I noticed a bug with the calendar displayed in the Events app. When there are no inputs in the color fields, the calendar highlight appears blank. I will address this bug and test more vigorously before I merge this.
> Add color fields to events app module again (Revert the revert)

- README.md
- resources/events.hubdb.json
- src/components/EventDetailsRegistration.js
- src/components/RegisteredEventListings.js
- src/event.functions/eventSignup.js
- src/event.functions/membership.js
- src/event.functions/serverless.json
I've been thinking about this problem a bit and wanted to put up a PR to get my thoughts down.
My main motivation here is to reduce the need for events to have a 1:1 relationship with forms, as I can see that becoming untenable pretty quick. 
The reason for using the forms submission API is so we can capture the `hubspotutk` cookie and associate it with a contact vid on submission. We don't necessarily need to use the form submission to update contacts with event-specific information -- once a visitor is a known a contact, we could update properties / associated information directly via a different API. Said another way, the form primarily just functions to to associate the cookie with contact.
It's also possible we could use a hidden field to pass an event unique identifier (such as a …
> Switch to a single form and use event slugs instead of form guids to differentiate

- src/components/EventDetails.js
- src/components/EventDetails.scss
Adds a previous and next link to the event details view to allow users to page through events:
Fixes #31
> Add basic pagination

- src/UpcomingEvents.js
Some time ago, we started fetching events already sorted by start date, though the upcoming events module wasn't updated. This change ensures the upcoming events module is displaying the next, upcoming three events instead of the last three.
> Un-reverse Upcoming Events module listing order

- src/modules/events-app.module/fields.json
- src/modules/events-app.module/module.html
Fixes #47.
I've regrouped and reorganized the color fields in the Events app into three groups: 1) Filter menu styles, 2) Card styles, and 3) Form. These three groups only appear if the customer toggles the 'Customize style' boolean, just as we discussed here (https://github.com/HubSpot/cms-event-registration/pull/27#discussion_r414103613). 
I encountered three main issues while working on this PR:
ISSUE 1: Originally, in her mock, Amanda suggested the third field group be the 'Event details style' group, which itself would have two groups: Form and Breadcrumb. While I was attempting to create the Event detail styles group, I received the following error in the Design Manager: 'Field groups can be nested at most 3 deep'. It won't be possible to implement the Event detail styles group with …
> Regroup and reorganize Events app color fields

- src/AppContext.js
- src/components/EventDetailsRegistration.js
- src/components/RegisteredEventListings.js
- src/event.functions/eventSignup.js
- src/event.functions/membership.js
- src/event.functions/serverless.json
Resolves #41 
* Renames `registration/new` -> `/register`
* Renames `registration` -> `/authenticate` and changes method to `GET`
* Throws 401 instead of 403 when a user is not signed in / a new visitor
* Adjusts error handling in `errorSignup.js (/register)` for events with an initial attendee count of 0.
> Improve endpoint error handling, naming, and methods

- package.json
Resolves #61 
Thanks for pointing this out @dannio! This never came up on our end because I believe the mac filesystem is case-insensitive and no one caught it.
> lowercase 'b' in createHubDb.js

- src/components/EventFilterBar.scss
I removed a leftover vendor prefix from the `EventFilterBar.scss` file.
> Remove a reference to webkit in scss file

- src/modules/events-app.module/module.html
Noticed the warning that the images were missing from within design manager. Not sure when they stopped being included/used.
> Remove unavailable images from events module

- src/components/AppHero.js
- src/components/AppHero.scss
- src/modules/events-app.module/fields.json
- src/scss/App.scss
Resolves #56 
TODO:
- I was misremembering this feature-- `resizable: false` will hide height / width, and I don't think there's a way to hide the alt text subfield in the module form UI for image fields.
> Add customizable hero img

- src/App.js
- src/AppContext.js
- src/components/ErrorPageEditor.js
- src/components/EventCard.js
- src/components/EventDetails.js
- src/event.functions/eventSignup.js
Fixes #84 
I have four main concerns at the moment: 
1) I've added a function in `AppContext.js` to filter events and to add default values, where values are missing. I've taken advantage of the lodash `defaults` method to do so, but I'm curious whether anyone else might have other ideas how to achieve this.
2) I have added default values for certain columns--do these defaults make sense to everyone?  
DEFAULTS SET: 
Name: 'Untitled event' 
Event Description: 'Missing event description'
Event Capacity: 25
Registered Eventee Count: 0
Attendance Type: Virtual 
3) Currently, if an event is missing the Page Title or Page Path columns, no warnings appear. Without the Page Path column in particular, the user cannot select the event card to navigate to the event details page without this value. …
> Add functionality to handle missing values in HubDB columns

- README.md
- src/App.js
- src/RegisteredEventsPage.js
- src/UpcomingEvents.js
- src/components/AppHero.js
- src/components/EventListings.js
- src/components/RegisteredEventListings.js
- src/components/RegistrationConfirmation.js
- src/index.js
- src/modules/events-app.module/fields.json
- src/modules/events-app.module/module.html
- src/modules/upcoming-events.module/fields.json
- src/modules/upcoming-events.module/module.html
Continuation of the work done by @anthmatic in #6 in the context of where we landed for https://github.com/HubSpot/cms-react-boilerplate
- Adds multiple instance support for both modules
- updates `{{ module }}` prior to sending to app to pre-evaluate any module data that requires extra HubL (like `content_by_id()`, `slug` -- I'm on the fence about this approach and could use some feedback)
- re-organizes the `module|tojson` pass in events app to remain consistent with the CMS React boilerplate
TODO:
> Revisit slug configuration

- src/event.functions/eventSignup.js
Per our discussions on Slack, I've refactored the event signup function, so that we: 
1) check the draft HubDB table for the registered attendee count, and 
2) compare the registered attendee count with the event capacity (if there is one). 
Only after these two steps do we increment the attendee count and update the HubDB table.
> Refactor event signup function

- src/App.js
- src/RegisteredEventsPage.js
- src/components/AppHero.js
- src/components/EventListings.js
- src/components/RegisteredEventListings.js
- src/components/RegistrationConfirmation.js
- src/index.js
- src/modules/events-app.module/fields.json
- src/modules/events-app.module/module.html
- src/scss/upcoming-events.scss
Since incorporating my and @levinkeo's changes to the module fields, I thought that the fields looked a bit disorganized while working in the page editor. 
I reordered and regrouped the different field groups for a (hopefully) more seamless editing experience. 
cc @achong07, @levinkeo (you might want to take a look to ensure that I've updated `moduleData` correctly in the `module.html` file).
> Reorder and regroup module fields

- src/modules/events-app.module/module.html
- src/modules/upcoming-events.module/fields.json
- src/modules/upcoming-events.module/module.html
While I was reviewing the app, I noticed that we hadn't updated the module fields for the Upcoming Events module in quite some time. 
I've updated the color fields in the Upcoming Events module to mirror those in the Events app module. There is a Customize Style toggle button which controls the Colors field group. The Colors field group contains a "Light color" color field, a "Dark color" color field, and a Colors scheme dropdown menu. I've omitted the "Link color" color field, because the Upcoming Events module has no links.
> Update Upcoming Events module with color schemes

- src/modules/events-app.module/fields.json
I've relabeled one of the Events app field groups from 'Hero Image Banner' to 'Hero Banner.'
> Relabel Hero Banner group

- resources/hs_events.hubdb.json
So that the events actually show up in the list of events (filtered for things that happen in the future).
Here is a quick little image to show what the new timestamps refer to:
> Update event start and end times to be in 2022
